### ISSUE TITLE
login/pass entry

### ISSUE THREAD

**Issue by zedmands** [zedmands/WheresMyStuff#2]
If someone selects Login, then you should display a way to enter the user name and password.
If someone requests login, you should check for the correct user name and password. For this first milestone, you may have a hard coded user with name "user" and password "pass" to check against.
If the login matches user name / password then go to your application. Otherwise, notify of the bad login attempt.
Canceling the login (press Cancel or going back a screen for example) will close out the login attempt , but no information is recorded and the application does not start up. Note here you are not explicitly required to have a cancel button, just a way to back out of the login.

**Comment by JamesRick** [comment]
Working on it

**Comment by JamesRick** [comment]
Currently the back button on the android ui serves as a cancel button for the Login Screen. We can add a dedicated cancel to it, but I don't think it is necessary.
